// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMjD49LDkDsmWxsVzSFs_Lt9KNS4PwoII',
    appId: '1:944635405729:web:7bb47e06a3d1c2f40e17e0',
    messagingSenderId: '944635405729',
    projectId: 'vibra-beb69',
    authDomain: 'vibra-beb69.firebaseapp.com',
    storageBucket: 'vibra-beb69.firebasestorage.app',
    measurementId: 'G-QKYTQHHVK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrdyESmuoPWrVO_WDrB3nZ20W1AEM3ZOw',
    appId: '1:944635405729:android:5596a86c6abd388a0e17e0',
    messagingSenderId: '944635405729',
    projectId: 'vibra-beb69',
    storageBucket: 'vibra-beb69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtuUSER5oCnxnMuffQQusHbQn7Dw8Hgko',
    appId: '1:944635405729:ios:df4d787663da31140e17e0',
    messagingSenderId: '944635405729',
    projectId: 'vibra-beb69',
    storageBucket: 'vibra-beb69.firebasestorage.app',
    androidClientId: '944635405729-1vd98359a8tbkkop52dp97ujfl0lr86c.apps.googleusercontent.com',
    iosClientId: '944635405729-abn90d14hejb3trs91uqtgs6f7iqnp7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtuUSER5oCnxnMuffQQusHbQn7Dw8Hgko',
    appId: '1:944635405729:ios:df4d787663da31140e17e0',
    messagingSenderId: '944635405729',
    projectId: 'vibra-beb69',
    storageBucket: 'vibra-beb69.firebasestorage.app',
    androidClientId: '944635405729-1vd98359a8tbkkop52dp97ujfl0lr86c.apps.googleusercontent.com',
    iosClientId: '944635405729-abn90d14hejb3trs91uqtgs6f7iqnp7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMjD49LDkDsmWxsVzSFs_Lt9KNS4PwoII',
    appId: '1:944635405729:web:bb4a2df3e1c0c8d00e17e0',
    messagingSenderId: '944635405729',
    projectId: 'vibra-beb69',
    authDomain: 'vibra-beb69.firebaseapp.com',
    storageBucket: 'vibra-beb69.firebasestorage.app',
    measurementId: 'G-96N19CDR5T',
  );
}
